In [1]:
import numpy as np

1. Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [2]:
a = np.arange(12, 24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

2. Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [27]:
b = a.reshape(6, 2)
c = a.reshape(2, 6)
d = a.reshape(3, 4)
e = a.reshape(4, 3)
f = a.reshape(12, 1)

b, c, d, e, f

(array([[ 0,  1],
        [ 2,  3],
        [ 4,  5],
        [ 6,  7],
        [ 8,  9],
        [10, 11]]),
 array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]),
 array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8],
        [ 9, 10, 11]]),
 array([[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10],
        [11]]))

3. Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [4]:
b = a.reshape(-1, 2)
c = a.reshape(-1, 6)
d = a.reshape(3, -1)
e = a.reshape(4, -1)
f = a.reshape(1, -1)

b, c, d, e, f

(array([[12, 13],
        [14, 15],
        [16, 17],
        [18, 19],
        [20, 21],
        [22, 23]]),
 array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]),
 array([[12, 13, 14],
        [15, 16, 17],
        [18, 19, 20],
        [21, 22, 23]]),
 array([[12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23]]))

4. Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

        Зависит от определения одномерного массива. Фактически у такого массива одна ось, вдоль которой изменяется индекс элементов (т.к. значение второй - 1), и можно получить любой элемент, обратившись к этой оси.
        Формально всё же - двумерный массив с одним столбцом (вектор-столбец, т.е. ориентированный вектор).

In [5]:
a = np.arange(12).reshape(12, 1)

# два измерения
print(np.shape(a), a.ndim)

(12, 1) 2


5.  - Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. 
    

In [6]:
x = np.random.sample((3, 4))
x

array([[0.3765755 , 0.27733614, 0.19288113, 0.11256468],
       [0.03017813, 0.1027393 , 0.02440353, 0.1665785 ],
       [0.04620731, 0.33679933, 0.99426415, 0.32904556]])

- Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.

In [7]:
y = x.flatten()
y, y.size == x.size

(array([0.3765755 , 0.27733614, 0.19288113, 0.11256468, 0.03017813,
        0.1027393 , 0.02440353, 0.1665785 , 0.04620731, 0.33679933,
        0.99426415, 0.32904556]),
 True)

6. Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [8]:
a = np.arange(20, 0, -2)
a

# или
# a = np.arange(2, 21, 2)
# a = np.flip(a, 0)

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

7. Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [9]:
b = np.arange(20, 1, -2).reshape(10, 1)
b

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

In [10]:
print(f'Форма a: {a.shape}, число измерений a: {a.ndim}.\nФорма b: {b.shape}, число измерений b: {b.ndim}')

Форма a: (10,), число измерений a: 1.
Форма b: (10, 1), число измерений b: 2


8. Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [11]:
a = np.zeros((2, 2))
b = np.ones((3, 2))

v = np.vstack((a, b))
# или
# np.concatenate((a, b), axis=0)

v, v.size

(array([[0., 0.],
        [0., 0.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]),
 10)

9.  - Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12.

In [12]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

- Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов.

In [28]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

- Получить матрицу At путем транспонирования матрицы A. 

In [14]:
At = A.T
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

- Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения.

In [34]:
B = A @ At
B

array([[  5,  14,  23,  32],
       [ 14,  50,  86, 122],
       [ 23,  86, 149, 212],
       [ 32, 122, 212, 302]])

- Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

По определению: умножаем матрицу A размером 4x3 на матрицу размером 3x4 получаем 4x4 (число столбцов первой матрицы совпадает с числом строк второй матрицы, в итоге -  матрица с числом *строк* как у первой и *столбцов* - как у второй)

In [35]:
B.size, B.shape

(16, (4, 4))

In [36]:
d = np.linalg.det(B)
print(d)

0.0


Так как d - определитель матрицы B - равен нулю, то посчитать обратную матрицу не получится: определитель обратной матрицы был бы равен 1/d, что вызывает некоторые проблемы

10. Инициализируйте генератор случайных числе с помощью объекта seed, равного 42.

In [37]:
np.random.seed(42)
np.random.random(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
np.random.seed(42)
np.random.random(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

11. Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно. 

In [39]:
c = np.random.randint(0, 16, 16)
print(c)

[ 6  9  2  6 10 10  7  4  3  7  7  2  5  4  1  7]


12. - Поменяйте его форму так, чтобы получилась квадратная матрица C. 

In [40]:
C = c.reshape(4, 4)
C

array([[ 6,  9,  2,  6],
       [10, 10,  7,  4],
       [ 3,  7,  7,  2],
       [ 5,  4,  1,  7]])

- Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10.

In [41]:
D = B + C * 10
D

array([[ 65, 104,  43,  92],
       [114, 150, 156, 162],
       [ 53, 156, 219, 232],
       [ 82, 162, 222, 372]])

- Вычислите определитель, ранг и обратную матрицу D_inv для D.

In [42]:
D_d = np.linalg.det(D)

D_r = np.linalg.matrix_rank(D)

D_inv = np.linalg.inv(D)

print(f'Определитель: {D_d}, ранг: {D_r}, обратная матрица:\n{D_inv}')

Определитель: -113544000.00000009, ранг: 4, обратная матрица:
[[-0.01028377  0.01901606 -0.01552473  0.0039442 ]
 [ 0.02029909 -0.01187416  0.01174487 -0.00717396]
 [-0.01361499  0.00766399  0.00475851 -0.00293807]
 [ 0.001552   -0.00359438 -0.00453234  0.00669626]]


13. - Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. 

In [43]:
D_inv = np.where(D_inv < 0, 0, 1)
D_inv

array([[0, 1, 0, 1],
       [1, 0, 1, 0],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

- Убедитесь, что в матрице D_inv остались только нули и единицы.

In [44]:
np.unique(D_inv) == [0, 1]

array([ True,  True])

- С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4. 

            Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.

In [45]:
E = np.where(D_inv == 1, B, C)
E

array([[  6,  14,   2,  32],
       [ 14,  10,  86,   4],
       [  3,  86, 149,   2],
       [ 32,   4,   1, 302]])